name: "Check and report Android Lint result"
description: "A GitHub Action to check and report Android Lint result"
inputs:
  result-path:
    description: "Path or glob path pattern for Android Lint result XML file"
    required: true
  ignore-warning:
    description: "Setting whether to ignore warnings"
    default: false
runs:
  using: "node16"
  main: "dist/index.js"
